# Copyright 2026 Yaroslav Mariukha
# SPDX-License-Identifier: Apache-2.0

[project]
name = "fpga-cocotb"
version = "0.1.0"
description = "Intel Platform designer and Avalon Stream cocotb helpers"
requires-python = ">=3.10"

authors = [
    { name = "Yaroslav Mariukha"  }
]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"